### ISSUE TITLE
Rainbow is a spectrum of colours on really-light-blue!!!!

### ISSUE THREAD

**Issue by pradyunsg** [betovelandia/rainbow-syntax#1]
Disclaimer: I would like to see this happen. But then again, I'm not very serious.

A rainbow AFAIK is a spectrum of colours, usually with a cloudy, blue-ish background. See here: https://en.wikipedia.org/wiki/Rainbow#/media/File:Double_Rainbow_in_Vermont.jpg

This syntax, AFAICS, isn't that. So, unless you plan on radically changing the colours, please change the name... :stuck_out_tongue_winking_eye:

**Comment by betovelandia** [comment]
Any suggestions ?

**Comment by pradyunsg** [comment]
First up, OP is really poorly written. Sorry about that. 

I would suggest changing the name of the Colour Scheme or changing the colours in the colour scheme. 

As changing the name would be a breaking change, I suggest that you make a release with a message about such a change, while  having simultaneous publishing on package control for both names, new and old. This can be followed by a permanent switch to the new name after a brief period of time, like 10 days or so.

Another way would be to do so would be to change the colours. This on the other hand, will also be a breaking change. Also, I am pretty sure this is not an option anyway.

**Comment by betovelandia** [comment]
Can you expand on the "poorly written" comment, other than the name of the theme not pleasing your idea of a rainbow ?

**Comment by pradyunsg** [comment]
No. That is indeed the jist of this issue.

**Comment by pradyunsg** [comment]
Is there going to be any changes?

**Comment by betovelandia** [comment]
no, sorry
